[package]
name = "grev"
authors = ["Daniel Mueller <deso@posteo.net>"]
version = "0.0.0"
edition = "2021"
license = "Apache-2.0 OR MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
