# Copyright (C) 2022-2025 Daniel Mueller <deso@posteo.net>
# SPDX-License-Identifier: 	Apache-2.0 OR MIT

name: Test

on:
  pull_request:
  push:

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  # Build without debug information enabled to decrease compilation time
  # and binary sizes in CI. This option is assumed to only have marginal
  # effects on the generated code, likely only in terms of section
  # arrangement. See
  # https://doc.rust-lang.org/cargo/reference/environment-variables.html
  # https://doc.rust-lang.org/rustc/codegen-options/index.html#debuginfo
  RUSTFLAGS: '-C debuginfo=0'

jobs:
  build:
    name: Build [${{ matrix.os }} ${{ matrix.rust }}]
    strategy:
      fail-fast: false
      matrix:
        # Please adjust README and `msrv` in .clippy.toml when bumping
        # version.
        rust: [1.56.0, stable]
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ matrix.rust }}
    - name: Build
      run:
        cargo build --lib --tests
  clippy:
    name: Lint with clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo clippy --lib --bins --tests --examples -- -A unknown_lints -D warnings
  cargo-doc:
    name: Generate documentation
    runs-on: ubuntu-latest
    env:
      RUSTDOCFLAGS: '-A unknown_lints -A renamed_and_removed_lints -D warnings'
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo doc --no-deps
